# Generated by Django 4.1.4 on 2023-01-10 23:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_box', models.CharField(blank=True, max_length=100, null=True)),
                ('number_packages', models.CharField(blank=True, max_length=50, null=True)),
                ('type_box', models.CharField(blank=True, choices=[('Liquide', 'Liquide'), ('Solide', 'Solide')], max_length=100, null=True)),
                ('etat', models.CharField(blank=True, choices=[('En coure ...', 'En coure ...'), ('Valider', 'Valider')], default='En coure ...', max_length=100, null=True)),
                ('date', models.CharField(blank=True, default='10-01-2023', max_length=100, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
