# Generated by Django 4.1.4 on 2023-02-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0002_alter_newbox_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbox',
            name='date',
            field=models.CharField(blank=True, default='01-02-2023', max_length=100, null=True),
        ),
    ]
