# Generated by Django 4.1.4 on 2023-02-04 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0004_alter_newbox_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbox',
            name='date',
            field=models.CharField(blank=True, default='04-02-2023', max_length=100, null=True),
        ),
    ]
