# Generated by Django 4.1.4 on 2023-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0008_alter_newbox_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbox',
            name='date',
            field=models.CharField(blank=True, default='18-05-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newbox',
            name='etat',
            field=models.CharField(blank=True, choices=[('Running...', 'Running...'), ('Validate', 'Validate')], default='Running...', max_length=100, null=True),
        ),
    ]
