# Generated by Django 4.1.4 on 2023-05-30 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0009_alter_newbox_date_alter_newbox_etat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newbox',
            name='date',
            field=models.CharField(blank=True, default='30-05-2023', max_length=100, null=True),
        ),
    ]
