# Generated by Django 4.0.6 on 2022-08-24 15:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Received',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received', models.BooleanField(blank=True, default=False, null=True)),
                ('received_id', models.CharField(blank=True, max_length=100, null=True)),
                ('received_date', models.DateTimeField(default=datetime.date.today)),
            ],
        ),
    ]
