# Generated by Django 4.0.6 on 2022-09-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0002_exchangerequest_newpackage_refundrequest_and_more'),
        ('pickup', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='received',
            name='received',
        ),
        migrations.RemoveField(
            model_name='received',
            name='received_date',
        ),
        migrations.AddField(
            model_name='received',
            name='packages',
            field=models.ManyToManyField(blank=True, to='packages.newpackage'),
        ),
        migrations.AddField(
            model_name='received',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
