# Generated by Django 4.0.6 on 2022-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0002_remove_received_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='date_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
