# Generated by Django 4.1.1 on 2022-09-19 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0003_received_date_received'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='receive',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
