# Generated by Django 4.1.1 on 2022-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0004_received_receive'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='total_amount',
            field=models.IntegerField(null=True),
        ),
    ]
