# Generated by Django 4.1.1 on 2022-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0005_received_total_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='total_withdrawn',
            field=models.IntegerField(null=True),
        ),
    ]
