# Generated by Django 4.1.1 on 2022-10-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0006_received_total_withdrawn'),
    ]

    operations = [
        migrations.AddField(
            model_name='received',
            name='invoise',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
