# Generated by Django 4.1.1 on 2022-12-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0007_received_invoise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='invoise',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='receive',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='total_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='received',
            name='total_withdrawn',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
