# Generated by Django 4.1.1 on 2022-12-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0008_alter_received_invoise_alter_received_receive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='received_id',
            field=models.CharField(blank=True, default='None', max_length=100, null=True),
        ),
    ]
