# Generated by Django 4.1.1 on 2022-12-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0009_alter_received_received_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='received',
            name='invoise',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
