# Generated by Django 4.0.6 on 2022-08-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewPackages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('remark', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=100)),
            ],
        ),
    ]
