# Generated by Django 4.0.6 on 2022-09-15 11:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_id', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange_price', models.CharField(blank=True, max_length=100, null=True)),
                ('exchange', models.TextField(null=True)),
                ('exchange_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_package', models.CharField(blank=True, max_length=100, null=True)),
                ('article_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('remark', models.TextField(max_length=300)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('phone_number', models.CharField(max_length=10)),
                ('client_name', models.CharField(max_length=100)),
                ('date_created', models.CharField(blank=True, default='15-09-2022 11:49', max_length=100, null=True)),
                ('etat', models.CharField(blank=True, choices=[('EN ATTENTE DE RAMASSAGE', 'EN ATTENTE DE RAMASSAGE'), ('Ramassée', 'Ramassée'), ('Annulée', 'Annulée'), ('Livrée', 'Livrée'), ('Pas de réponse', 'Pas de réponse'), ('Retournée/Annulée', 'Retournée/Annulée')], default='EN ATTENTE DE RAMASSAGE', max_length=100, null=True)),
                ('picked_up', models.BooleanField(blank=True, default=False, null=True)),
                ('date_picked_up', models.CharField(blank=True, default='15-09-2022 11:49', max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('refund_price', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('refund', models.TextField(null=True, unique=True)),
                ('refund_date', models.DateTimeField(auto_now_add=True, unique=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.newpackage')),
            ],
        ),
        migrations.DeleteModel(
            name='NewPackages',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='packages.newpackage'),
        ),
    ]
