# Generated by Django 4.0.6 on 2022-09-15 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_exchangerequest_newpackage_refundrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='15-09-2022 11:57', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='15-09-2022 11:57', max_length=100, null=True),
        ),
    ]
