# Generated by Django 4.1.1 on 2022-09-22 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpackage',
            name='amount_withdrawn',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='22-09-2022 13:40', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='22-09-2022 13:40', max_length=100, null=True),
        ),
    ]
