# Generated by Django 4.1.1 on 2022-09-22 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_newpackage_amount_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='22-09-2022 14:28', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='22-09-2022 14:28', max_length=100, null=True),
        ),
    ]
