# Generated by Django 4.1.1 on 2022-09-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_alter_newpackage_amount_withdrawn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='amount_withdrawn',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
