# Generated by Django 4.1.1 on 2022-10-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newpackage',
            old_name='amount_withdrawn',
            new_name='withdrawn_canceled',
        ),
        migrations.AddField(
            model_name='newpackage',
            name='withdrawn_livery',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='newpackage',
            name='withdrawn_refused',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='15-10-2022 22:19', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='15-10-2022 22:19', max_length=100, null=True),
        ),
    ]
