# Generated by Django 4.1.1 on 2022-10-18 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0013_rename_amount_withdrawn_newpackage_withdrawn_canceled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='18-10-2022 00:37', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='18-10-2022 00:37', max_length=100, null=True),
        ),
    ]
