# Generated by Django 4.1.1 on 2022-10-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0022_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='30-10-2022', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='30-10-2022', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
