# Generated by Django 4.1.1 on 2022-12-13 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('packages', '0026_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchangerequest',
            name='package',
        ),
        migrations.RemoveField(
            model_name='refundrequest',
            name='package',
        ),
        migrations.AddField(
            model_name='exchangerequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='refundrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='13-12-2022', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='13-12-2022', max_length=100, null=True),
        ),
    ]
