# Generated by Django 4.1.4 on 2023-02-01 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0038_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refundrequest',
            name='refund_price',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
