# Generated by Django 4.1.4 on 2023-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0039_alter_refundrequest_refund_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpackage',
            name='exchange',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='02-02-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='02-02-2023', max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='ExchangeRequest',
        ),
    ]
