# Generated by Django 4.1.4 on 2023-05-18 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0044_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='18-05-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='18-05-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='etat',
            field=models.CharField(blank=True, choices=[('WAITING FOR PICKUP', 'WAITING FOR PICKUP'), ('In progress...', 'In progress...'), ('Exchange', 'Exchange'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refused', 'Refused'), ('No answer', 'No answer'), ('Returned/Cancelled', 'Returned/Cancelled'), ('Go back/Exchange', 'Go back/Exchange'), ('Returned/Refused', 'Returned/Refused')], default='WAITING FOR PICKUP', max_length=100, null=True),
        ),
    ]
