# Generated by Django 4.1.4 on 2023-06-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0011_alter_newbox_date'),
        ('packages', '0046_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newpackage',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxPackages.newbox'),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='03-06-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='03-06-2023', max_length=100, null=True),
        ),
    ]
