# Generated by Django 4.1.4 on 2023-06-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0047_newpackage_box_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='address',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='article_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='city',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='client_name',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='26-06-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='26-06-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='etat',
            field=models.CharField(choices=[('WAITING FOR PICKUP', 'WAITING FOR PICKUP'), ('In progress...', 'In progress...'), ('Exchange', 'Exchange'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refused', 'Refused'), ('No answer', 'No answer'), ('Returned/Cancelled', 'Returned/Cancelled'), ('Go back/Exchange', 'Go back/Exchange'), ('Returned/Refused', 'Returned/Refused')], default='WAITING FOR PICKUP', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='id_package',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='phone_number',
            field=models.CharField(default='None', max_length=10),
        ),
    ]
