# Generated by Django 4.1.4 on 2023-06-27 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0013_alter_newbox_date'),
        ('packages', '0048_alter_newpackage_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='box',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='boxPackages.newbox'),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_created',
            field=models.CharField(blank=True, default='27-06-2023', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='date_picked_up',
            field=models.CharField(blank=True, default='27-06-2023', max_length=100, null=True),
        ),
    ]
