# Generated by Django 4.1.4 on 2023-06-27 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0049_alter_newpackage_box_alter_newpackage_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='article_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='client_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='id_package',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='newpackage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
