# Generated by Django 4.1.4 on 2023-06-27 02:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('boxPackages', '0013_alter_newbox_date'),
        ('packages', '0050_alter_newpackage_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='box',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='boxPackages.newbox'),
        ),
    ]
