# Generated by Django 4.1.4 on 2023-06-27 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0051_alter_newpackage_box'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='phone_number',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
