# Generated by Django 4.1.4 on 2023-06-27 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0052_alter_newpackage_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newpackage',
            name='etat',
            field=models.CharField(blank=True, choices=[('WAITING FOR PICKUP', 'WAITING FOR PICKUP'), ('In progress...', 'In progress...'), ('Exchange', 'Exchange'), ('Picked Up', 'Picked Up'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered'), ('Refused', 'Refused'), ('No answer', 'No answer'), ('Returned/Cancelled', 'Returned/Cancelled'), ('Go back/Exchange', 'Go back/Exchange'), ('Returned/Refused', 'Returned/Refused')], default='WAITING FOR PICKUP', max_length=100, null=True),
        ),
    ]
