# Generated by Django 4.1.1 on 2022-12-17 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddPackage',
        ),
    ]
