# Generated by Django 4.1.1 on 2022-12-17 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0031_alter_newpackage_date_created_and_more'),
        ('adminManager', '0002_delete_addpackage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_delivery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminManager.profilemandelivery')),
                ('packages', models.ManyToManyField(blank=True, to='packages.newpackage')),
            ],
        ),
    ]
