# Generated by Django 4.1.1 on 2022-12-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminManager', '0003_addpackage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addpackage',
            old_name='packages',
            new_name='set_packages',
        ),
    ]
