# Generated by Django 4.1.1 on 2022-12-18 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0032_alter_newpackage_date_created_and_more'),
        ('adminManager', '0004_rename_packages_addpackage_set_packages'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemandelivery',
            name='set_packages',
            field=models.ManyToManyField(blank=True, to='packages.newpackage'),
        ),
    ]
