# Generated by Django 4.1.4 on 2023-02-01 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_profile_total_money_net'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_money_net',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
