# Generated by Django 4.1.4 on 2023-05-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_alter_profile_business_name_alter_profile_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rip',
            field=models.CharField(max_length=27),
        ),
    ]
