# Generated by Django 4.1.4 on 2023-01-05 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0002_alter_contact_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date',
            field=models.CharField(blank=True, default='05-01-2023', max_length=100, null=True),
        ),
    ]
