# Generated by Django 4.1.4 on 2023-02-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactUs', '0005_alter_contact_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date',
            field=models.CharField(blank=True, default='02-02-2023', max_length=100, null=True),
        ),
    ]
