# Generated by Django 4.1.4 on 2023-01-04 00:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pickup', '0010_alter_received_invoise'),
        ('tracking', '0003_alter_tracking_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tracking',
            old_name='id_package',
            new_name='id_received',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='package',
        ),
        migrations.AddField(
            model_name='tracking',
            name='received',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pickup.received'),
        ),
    ]
